import { useState } from "react"
import { useQuery } from "@tanstack/react-query"
import * as reportService from "@/services/report.service"
import type { DailyReport } from "@/services/report.service"
import { useAuth } from "@/context/AuthContext"
import { useActiveBusiness } from "@/hooks/useActiveBusiness"
import { formatDate, formatMoney } from "@/lib/format"
import { downloadCsv } from "@/lib/csv"
import { downloadPdfReport } from "@/lib/pdf"
import { EmptyState } from "@/components/EmptyState"
import { ErrorState } from "@/components/ErrorState"
import { SummaryStat } from "@/components/reports/SummaryStat"
import { DownloadMenu } from "@/components/reports/DownloadMenu"
import { Input } from "@/components/ui/input"
import { Skeleton } from "@/components/ui/skeleton"
import { CalendarDays } from "lucide-react"

function todayIso() {
  return new Date().toISOString().slice(0, 10)
}

function itemsSoldCsvRows(report: DailyReport, currency: string) {
  return [
    ["Items sold", report.date],
    ["Currency", currency],
    [],
    ["Product", "Quantity", "Revenue"],
    ...report.byProduct.map((row) => [row.product.name, row.totalQuantity, row.totalRevenue]),
    [],
    ["Total", "", report.summary.totalAmount],
  ]
}

function fullReportCsvRows(report: DailyReport, currency: string) {
  return [
    ["Daily report", report.date],
    ["Currency", currency],
    [],
    ["Total sales", report.summary.totalAmount],
    ["Transactions", report.summary.totalTransactions],
    ["Cash", report.summary.cashTotal],
    ["Transfer", report.summary.transferTotal],
    [],
    ["By employee"],
    ["Employee", "Total", "Cash", "Transfer"],
    ...report.byEmployee.map((row) => [row.employee.fullName, row.totalAmount, row.cashAmount, row.transferAmount]),
    [],
    ["By product"],
    ["Product", "Quantity", "Revenue"],
    ...report.byProduct.map((row) => [row.product.name, row.totalQuantity, row.totalRevenue]),
  ]
}

export function DailyReportTab() {
  const { activeBusinessId } = useAuth()
  const activeBusiness = useActiveBusiness()
  const currency = activeBusiness?.currency ?? "USD"
  const [date, setDate] = useState(todayIso)

  const query = useQuery({
    queryKey: ["report-daily", activeBusinessId, date],
    queryFn: () => reportService.getDailyReport(activeBusinessId!, date),
    enabled: !!activeBusinessId,
  })

  const pdfHeader = () => ({
    businessName: activeBusiness?.name ?? "",
    businessLocation: activeBusiness?.location,
    title: "DAILY REPORT",
    dateLine: formatDate(query.data!.date),
  })

  const downloadItemsCsv = () => {
    if (!query.data) return
    downloadCsv(`daily-items-sold-${query.data.date}.csv`, itemsSoldCsvRows(query.data, currency))
  }
  const downloadItemsPdf = () => {
    if (!query.data) return
    const report = query.data
    downloadPdfReport(`daily-items-sold-${report.date}.pdf`, {
      ...pdfHeader(),
      sections: [
        {
          head: ["Product", "Quantity", "Revenue"],
          body: report.byProduct.map((row) => [row.product.name, row.totalQuantity, formatMoney(row.totalRevenue, currency)]),
          foot: ["Total", "", formatMoney(report.summary.totalAmount, currency)],
        },
      ],
      footerNote: "Generated by D-Inventory",
    })
  }
  const downloadFullCsv = () => {
    if (!query.data) return
    downloadCsv(`daily-report-${query.data.date}.csv`, fullReportCsvRows(query.data, currency))
  }
  const downloadFullPdf = () => {
    if (!query.data) return
    const report = query.data
    downloadPdfReport(`daily-report-${report.date}.pdf`, {
      ...pdfHeader(),
      sections: [
        {
          heading: "Summary",
          head: ["Metric", "Value"],
          body: [
            ["Total sales", formatMoney(report.summary.totalAmount, currency)],
            ["Transactions", report.summary.totalTransactions],
            ["Cash", formatMoney(report.summary.cashTotal, currency)],
            ["Transfer", formatMoney(report.summary.transferTotal, currency)],
          ],
        },
        {
          heading: "By employee",
          head: ["Employee", "Total", "Cash", "Transfer"],
          body: report.byEmployee.map((row) => [
            row.employee.fullName,
            formatMoney(row.totalAmount, currency),
            formatMoney(row.cashAmount, currency),
            formatMoney(row.transferAmount, currency),
          ]),
        },
        {
          heading: "By product",
          head: ["Product", "Quantity", "Revenue"],
          body: report.byProduct.map((row) => [row.product.name, row.totalQuantity, formatMoney(row.totalRevenue, currency)]),
          foot: ["Total", "", formatMoney(report.summary.totalAmount, currency)],
        },
      ],
      footerNote: "Generated by D-Inventory",
    })
  }

  const dateControls = (
    <div className="flex flex-wrap items-center gap-2">
      <Input type="date" value={date} onChange={(e) => setDate(e.target.value)} className="w-auto" />
      <DownloadMenu
        className="ml-auto"
        disabled={!query.data}
        groups={[
          { label: "Items sold", items: [{ label: "CSV", onClick: downloadItemsCsv }, { label: "PDF", onClick: downloadItemsPdf }] },
          { label: "Full report", items: [{ label: "CSV", onClick: downloadFullCsv }, { label: "PDF", onClick: downloadFullPdf }] },
        ]}
      />
    </div>
  )

  if (query.isLoading) {
    return (
      <div className="space-y-4">
        {dateControls}
        <Skeleton className="h-64 rounded-xl" />
      </div>
    )
  }
  if (query.isError) {
    return (
      <div className="space-y-4">
        {dateControls}
        <ErrorState onRetry={() => query.refetch()} />
      </div>
    )
  }
  const report = query.data
  if (!report) return null

  if (report.summary.totalTransactions === 0) {
    return (
      <div className="space-y-4">
        {dateControls}
        <EmptyState icon={<CalendarDays className="size-6" />} title="No sales that day" description={report.date} />
      </div>
    )
  }

  return (
    <div className="space-y-4">
      {dateControls}
      <div className="grid grid-cols-2 gap-4 md:grid-cols-4">
        <SummaryStat label="Total sales" value={formatMoney(report.summary.totalAmount, currency)} />
        <SummaryStat label="Transactions" value={report.summary.totalTransactions} />
        <SummaryStat label="Cash" value={formatMoney(report.summary.cashTotal, currency)} />
        <SummaryStat label="Transfer" value={formatMoney(report.summary.transferTotal, currency)} />
      </div>

      <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
        <div className="rounded-xl border border-border p-4">
          <h3 className="mb-3 text-sm font-semibold">By employee</h3>
          <ul className="space-y-2 text-sm">
            {report.byEmployee.map((row) => (
              <li key={row.employee.id} className="flex justify-between">
                <span>{row.employee.fullName}</span>
                <span className="font-medium">{formatMoney(row.totalAmount, currency)}</span>
              </li>
            ))}
          </ul>
        </div>
        <div className="rounded-xl border border-border p-4">
          <h3 className="mb-3 text-sm font-semibold">By product</h3>
          <ul className="space-y-2 text-sm">
            {report.byProduct.map((row) => (
              <li key={row.product.id} className="flex justify-between">
                <span>
                  {row.product.name} × {row.totalQuantity}
                </span>
                <span className="font-medium">{formatMoney(row.totalRevenue, currency)}</span>
              </li>
            ))}
          </ul>
        </div>
      </div>
    </div>
  )
}
