import { useState } from "react"
import { useQuery } from "@tanstack/react-query"
import * as reportService from "@/services/report.service"
import { useAuth } from "@/context/AuthContext"
import { useActiveBusiness } from "@/hooks/useActiveBusiness"
import { formatMoney } from "@/lib/format"
import { downloadCsv } from "@/lib/csv"
import { downloadPdfReport } from "@/lib/pdf"
import { EmptyState } from "@/components/EmptyState"
import { ErrorState } from "@/components/ErrorState"
import { DownloadMenu } from "@/components/reports/DownloadMenu"
import { Input } from "@/components/ui/input"
import { Skeleton } from "@/components/ui/skeleton"
import { Users } from "lucide-react"

function todayIso() {
  return new Date().toISOString().slice(0, 10)
}

function firstOfMonthIso() {
  const d = new Date()
  return new Date(d.getFullYear(), d.getMonth(), 1).toISOString().slice(0, 10)
}

export function EmployeeReportTab() {
  const { activeBusinessId } = useAuth()
  const activeBusiness = useActiveBusiness()
  const currency = activeBusiness?.currency ?? "USD"
  const [startDate, setStartDate] = useState(firstOfMonthIso)
  const [endDate, setEndDate] = useState(todayIso)

  const query = useQuery({
    queryKey: ["report-employees", activeBusinessId, startDate, endDate],
    queryFn: () => reportService.getEmployeeReport(activeBusinessId!, startDate, endDate),
    enabled: !!activeBusinessId,
  })

  const downloadAsCsv = () => {
    if (!query.data) return
    const report = query.data
    downloadCsv(`employee-report-${report.startDate}-to-${report.endDate}.csv`, [
      ["Employee report", `${report.startDate} to ${report.endDate}`],
      ["Currency", currency],
      [],
      ["Employee", "Role", "Total", "Transactions", "Cash", "Transfer"],
      ...report.employees.map((e) => [
        e.employee.fullName,
        e.businessRole,
        e.summary.totalAmount,
        e.summary.transactionCount,
        e.summary.cashTotal,
        e.summary.transferTotal,
      ]),
    ])
  }

  const downloadAsPdf = () => {
    if (!query.data) return
    const report = query.data
    downloadPdfReport(`employee-report-${report.startDate}-to-${report.endDate}.pdf`, {
      businessName: activeBusiness?.name ?? "",
      businessLocation: activeBusiness?.location,
      title: "EMPLOYEE REPORT",
      dateLine: `${report.startDate} to ${report.endDate}`,
      sections: [
        {
          head: ["Employee", "Role", "Total", "Transactions", "Cash", "Transfer"],
          body: report.employees.map((e) => [
            e.employee.fullName,
            e.businessRole,
            formatMoney(e.summary.totalAmount, currency),
            e.summary.transactionCount,
            formatMoney(e.summary.cashTotal, currency),
            formatMoney(e.summary.transferTotal, currency),
          ]),
        },
      ],
      footerNote: "Generated by D-Inventory",
    })
  }

  const dateControls = (
    <div className="flex flex-wrap items-center gap-2">
      <Input type="date" value={startDate} onChange={(e) => setStartDate(e.target.value)} className="w-auto" />
      <span className="text-xs text-muted-foreground">to</span>
      <Input type="date" value={endDate} onChange={(e) => setEndDate(e.target.value)} className="w-auto" />
      <DownloadMenu
        className="ml-auto"
        disabled={!query.data}
        groups={[{ items: [{ label: "CSV", onClick: downloadAsCsv }, { label: "PDF", onClick: downloadAsPdf }] }]}
      />
    </div>
  )

  if (query.isLoading) {
    return (
      <div className="space-y-4">
        {dateControls}
        <Skeleton className="h-64 rounded-xl" />
      </div>
    )
  }
  if (query.isError) {
    return (
      <div className="space-y-4">
        {dateControls}
        <ErrorState onRetry={() => query.refetch()} />
      </div>
    )
  }
  const report = query.data
  if (!report) return null

  if (report.employees.length === 0) {
    return (
      <div className="space-y-4">
        {dateControls}
        <EmptyState icon={<Users className="size-6" />} title="No employee activity" description="No sales recorded by any employee in this period." />
      </div>
    )
  }

  return (
    <div className="space-y-4">
      {dateControls}
      <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
        {report.employees.map(({ employee, businessRole, summary, topProducts }) => (
          <div key={employee.id} className="rounded-xl border border-border p-4">
            <div className="mb-3 flex items-start justify-between">
              <div>
                <h3 className="font-heading text-sm font-semibold">{employee.fullName}</h3>
                <p className="text-xs text-muted-foreground">{businessRole}</p>
              </div>
              <p className="text-right font-medium">{formatMoney(summary.totalAmount, currency)}</p>
            </div>
            <div className="mb-3 grid grid-cols-3 gap-2 text-center text-xs">
              <div>
                <p className="font-semibold">{summary.transactionCount}</p>
                <p className="text-muted-foreground">Sales</p>
              </div>
              <div>
                <p className="font-semibold">{formatMoney(summary.cashTotal, currency)}</p>
                <p className="text-muted-foreground">Cash</p>
              </div>
              <div>
                <p className="font-semibold">{formatMoney(summary.transferTotal, currency)}</p>
                <p className="text-muted-foreground">Transfer</p>
              </div>
            </div>
            {topProducts.length > 0 && (
              <div>
                <p className="mb-1 text-xs font-medium text-muted-foreground">Top products</p>
                <ul className="space-y-1 text-sm">
                  {topProducts.map((row) => (
                    <li key={row.product.id} className="flex justify-between">
                      <span>{row.product.name}</span>
                      <span className="text-muted-foreground">× {row.totalQuantity}</span>
                    </li>
                  ))}
                </ul>
              </div>
            )}
          </div>
        ))}
      </div>
    </div>
  )
}
