import { useState } from "react"
import { useQuery } from "@tanstack/react-query"
import * as reportService from "@/services/report.service"
import type { MonthlyReport } from "@/services/report.service"
import { useAuth } from "@/context/AuthContext"
import { useActiveBusiness } from "@/hooks/useActiveBusiness"
import { formatMoney } from "@/lib/format"
import { downloadCsv } from "@/lib/csv"
import { downloadPdfReport } from "@/lib/pdf"
import { EmptyState } from "@/components/EmptyState"
import { ErrorState } from "@/components/ErrorState"
import { SummaryStat } from "@/components/reports/SummaryStat"
import { DownloadMenu } from "@/components/reports/DownloadMenu"
import { Input } from "@/components/ui/input"
import { Skeleton } from "@/components/ui/skeleton"
import { CalendarDays } from "lucide-react"
import { useTranslation } from "react-i18next"

// Current month as YYYY-MM, the default value for the month picker.
function currentMonthIso() {
  return new Date().toISOString().slice(0, 7)
}

// Builds CSV rows for the "Items sold" export: per-product quantity/revenue plus a total row.
function itemsSoldCsvRows(report: MonthlyReport, currency: string) {
  return [
    ["Items sold", report.month],
    ["Currency", currency],
    [],
    ["Product", "Quantity", "Revenue"],
    ...report.byProduct.map((row) => [row.product.name, row.totalQuantity, row.totalRevenue]),
    [],
    ["Total", "", report.summary.totalAmount],
  ]
}

// Builds CSV rows for the "Full report" export: summary totals, a daily breakdown,
// and breakdowns by employee and by product.
function fullReportCsvRows(report: MonthlyReport, currency: string) {
  return [
    ["Monthly report", report.month],
    ["Currency", currency],
    [],
    ["Total sales", report.summary.totalAmount],
    ["Transactions", report.summary.totalTransactions],
    ["Avg / day", report.summary.avgDailySales ?? 0],
    ["Best day", report.summary.bestDay?.dayName ?? ""],
    [],
    ["Daily breakdown"],
    ["Date", "Day", "Total", "Transactions"],
    ...report.dailyBreakdown.map((d) => [d.date, d.dayName, d.totalAmount, d.transactionCount]),
    [],
    ["By employee"],
    ["Employee", "Total", "Transactions"],
    ...report.byEmployee.map((row) => [row.employee.fullName, row.totalAmount, row.transactionCount]),
    [],
    ["By product"],
    ["Product", "Quantity", "Revenue"],
    ...report.byProduct.map((row) => [row.product.name, row.totalQuantity, row.totalRevenue]),
  ]
}

/**
 * Reports tab showing sales for a selected calendar month: total sales, transaction
 * count, average per day, best day, a daily bar chart, and breakdowns by employee and
 * by product. Includes "Items sold" and "Full report" exports (CSV/PDF).
 */
export function MonthlyReportTab() {
  const { t } = useTranslation()
  const { activeBusinessId } = useAuth()
  const activeBusiness = useActiveBusiness()
  const currency = activeBusiness?.currency ?? "USD"
  const [month, setMonth] = useState(currentMonthIso)
  // The <input type="month"> value ("YYYY-MM") is split into numeric year/month for the query.
  const [year, monthNum] = month.split("-").map(Number)

  const query = useQuery({
    queryKey: ["report-monthly", activeBusinessId, year, monthNum],
    queryFn: () => reportService.getMonthlyReport(activeBusinessId!, year, monthNum),
    enabled: !!activeBusinessId,
  })

  // Shared header fields for every PDF export below.
  const pdfHeader = () => ({
    businessName: activeBusiness?.name ?? "",
    businessLocation: activeBusiness?.location,
    title: "MONTHLY REPORT",
    dateLine: query.data!.month,
  })

  const downloadItemsCsv = () => {
    if (!query.data) return
    downloadCsv(`monthly-items-sold-${query.data.monthStart.slice(0, 7)}.csv`, itemsSoldCsvRows(query.data, currency))
  }
  const downloadItemsPdf = () => {
    if (!query.data) return
    const report = query.data
    downloadPdfReport(`monthly-items-sold-${report.monthStart.slice(0, 7)}.pdf`, {
      ...pdfHeader(),
      sections: [
        {
          head: ["Product", "Quantity", "Revenue"],
          body: report.byProduct.map((row) => [row.product.name, row.totalQuantity, formatMoney(row.totalRevenue, currency)]),
          foot: ["Total", "", formatMoney(report.summary.totalAmount, currency)],
        },
      ],
      footerNote: "Generated by VAE Inventory",
    })
  }
  const downloadFullCsv = () => {
    if (!query.data) return
    downloadCsv(`monthly-report-${query.data.monthStart.slice(0, 7)}.csv`, fullReportCsvRows(query.data, currency))
  }
  const downloadFullPdf = () => {
    if (!query.data) return
    const report = query.data
    downloadPdfReport(`monthly-report-${report.monthStart.slice(0, 7)}.pdf`, {
      ...pdfHeader(),
      sections: [
        {
          heading: "Summary",
          head: ["Metric", "Value"],
          body: [
            ["Total sales", formatMoney(report.summary.totalAmount, currency)],
            ["Transactions", report.summary.totalTransactions],
            ["Avg / day", formatMoney(report.summary.avgDailySales ?? 0, currency)],
            ["Best day", report.summary.bestDay?.dayName ?? ""],
          ],
        },
        {
          heading: "Daily breakdown",
          head: ["Date", "Day", "Total", "Transactions"],
          body: report.dailyBreakdown.map((d) => [d.date, d.dayName, formatMoney(d.totalAmount, currency), d.transactionCount]),
        },
        {
          heading: "By employee",
          head: ["Employee", "Total", "Transactions"],
          body: report.byEmployee.map((row) => [row.employee.fullName, formatMoney(row.totalAmount, currency), row.transactionCount]),
        },
        {
          heading: "By product",
          head: ["Product", "Quantity", "Revenue"],
          body: report.byProduct.map((row) => [row.product.name, row.totalQuantity, formatMoney(row.totalRevenue, currency)]),
          foot: ["Total", "", formatMoney(report.summary.totalAmount, currency)],
        },
      ],
      footerNote: "Generated by VAE Inventory",
    })
  }

  const dateControls = (
    <div className="flex flex-wrap items-center gap-2">
      <Input type="month" value={month} onChange={(e) => setMonth(e.target.value)} className="w-auto" />
      <DownloadMenu
        className="ml-auto"
        disabled={!query.data}
        groups={[
          { label: "Items sold", items: [{ label: "CSV", onClick: downloadItemsCsv }, { label: "PDF", onClick: downloadItemsPdf }] },
          { label: "Full report", items: [{ label: "CSV", onClick: downloadFullCsv }, { label: "PDF", onClick: downloadFullPdf }] },
        ]}
      />
    </div>
  )

  if (query.isLoading) {
    return (
      <div className="space-y-4">
        {dateControls}
        <Skeleton className="h-64 rounded-xl" />
      </div>
    )
  }
  if (query.isError) {
    return (
      <div className="space-y-4">
        {dateControls}
        <ErrorState onRetry={() => query.refetch()} />
      </div>
    )
  }
  const report = query.data
  if (!report) return null

  if (report.summary.totalTransactions === 0) {
    return (
      <div className="space-y-4">
        {dateControls}
        <EmptyState icon={<CalendarDays className="size-6" />} title="No sales this month" description={report.month} />
      </div>
    )
  }

  // Denominator for the daily-breakdown bar heights; floored at 1 to avoid divide-by-zero.
  const maxDayAmount = Math.max(...report.dailyBreakdown.map((d) => d.totalAmount), 1)

  return (
    <div className="space-y-4">
      {dateControls}
      <div className="grid grid-cols-2 gap-4 md:grid-cols-4">
        <SummaryStat label="Total sales" value={formatMoney(report.summary.totalAmount, currency)} />
        <SummaryStat label="Transactions" value={report.summary.totalTransactions} />
        <SummaryStat label="Avg / day" value={formatMoney(report.summary.avgDailySales ?? 0, currency)} />
        <SummaryStat label="Best day" value={report.summary.bestDay ? report.summary.bestDay.dayName : "—"} />
      </div>

      <div className="rounded-xl border border-border p-4">
        <h3 className="mb-3 text-sm font-semibold">{t("Daily breakdown")}</h3>
        <div className="flex h-32 items-end gap-1">
          {report.dailyBreakdown.map((day) => (
            <div
              key={day.date}
              title={`${day.dayName}: ${formatMoney(day.totalAmount, currency)}`}
              className="flex-1 rounded-t bg-gradient-to-t from-primary to-success opacity-70 transition-opacity hover:opacity-100"
              style={{ height: `${Math.max((day.totalAmount / maxDayAmount) * 100, 2)}%` }}
            />
          ))}
        </div>
      </div>

      <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
        <div className="rounded-xl border border-border p-4">
          <h3 className="mb-3 text-sm font-semibold">{t("By employee")}</h3>
          <ul className="space-y-2 text-sm">
            {report.byEmployee.map((row) => (
              <li key={row.employee.id} className="flex justify-between">
                <span>{row.employee.fullName}</span>
                <span className="font-medium">{formatMoney(row.totalAmount, currency)}</span>
              </li>
            ))}
          </ul>
        </div>
        <div className="rounded-xl border border-border p-4">
          <h3 className="mb-3 text-sm font-semibold">{t("By product")}</h3>
          <ul className="space-y-2 text-sm">
            {report.byProduct.map((row) => (
              <li key={row.product.id} className="flex justify-between">
                <span>
                  {row.product.name} × {row.totalQuantity}
                </span>
                <span className="font-medium">{formatMoney(row.totalRevenue, currency)}</span>
              </li>
            ))}
          </ul>
        </div>
      </div>
    </div>
  )
}
