import { useState } from "react"
import { useQuery } from "@tanstack/react-query"
import * as reportService from "@/services/report.service"
import type { ProductReportItem } from "@/services/report.service"
import { useAuth } from "@/context/AuthContext"
import { useActiveBusiness } from "@/hooks/useActiveBusiness"
import { formatMoney } from "@/lib/format"
import { downloadCsv } from "@/lib/csv"
import { downloadPdfReport } from "@/lib/pdf"
import { EmptyState } from "@/components/EmptyState"
import { ErrorState } from "@/components/ErrorState"
import { DownloadMenu } from "@/components/reports/DownloadMenu"
import { Input } from "@/components/ui/input"
import { Skeleton } from "@/components/ui/skeleton"
import { Package } from "lucide-react"

function todayIso() {
  return new Date().toISOString().slice(0, 10)
}

function firstOfMonthIso() {
  const d = new Date()
  return new Date(d.getFullYear(), d.getMonth(), 1).toISOString().slice(0, 10)
}

function ProductList({ items, currency, metric }: { items: ProductReportItem[]; currency: string; metric: "revenue" | "quantity" }) {
  return (
    <ul className="space-y-2 text-sm">
      {items.map((row) => (
        <li key={row.product.id} className="flex items-center justify-between">
          <div>
            <p className="font-medium">{row.product.name}</p>
            <p className="text-xs text-muted-foreground">
              {row.currentStock.total} {row.product.unit} in stock
            </p>
          </div>
          <span className="font-medium">
            {metric === "revenue" ? formatMoney(row.totalRevenue, currency) : `${row.totalQuantity} ${row.product.unit}`}
          </span>
        </li>
      ))}
    </ul>
  )
}

export function ProductReportTab() {
  const { activeBusinessId } = useAuth()
  const activeBusiness = useActiveBusiness()
  const currency = activeBusiness?.currency ?? "USD"
  const [startDate, setStartDate] = useState(firstOfMonthIso)
  const [endDate, setEndDate] = useState(todayIso)

  const query = useQuery({
    queryKey: ["report-products", activeBusinessId, startDate, endDate],
    queryFn: () => reportService.getProductReport(activeBusinessId!, startDate, endDate),
    enabled: !!activeBusinessId,
  })

  const downloadAsCsv = () => {
    if (!query.data) return
    const report = query.data
    downloadCsv(`product-report-${report.startDate}-to-${report.endDate}.csv`, [
      ["Product report", `${report.startDate} to ${report.endDate}`],
      ["Currency", currency],
      [],
      ["Product", "Quantity sold", "Revenue", "Avg unit price", "Current stock"],
      ...report.bestSelling.map((row) => [
        row.product.name,
        row.totalQuantity,
        row.totalRevenue,
        row.avgUnitPrice,
        row.currentStock.total,
      ]),
    ])
  }

  const downloadAsPdf = () => {
    if (!query.data) return
    const report = query.data
    downloadPdfReport(`product-report-${report.startDate}-to-${report.endDate}.pdf`, {
      businessName: activeBusiness?.name ?? "",
      businessLocation: activeBusiness?.location,
      title: "PRODUCT REPORT",
      dateLine: `${report.startDate} to ${report.endDate}`,
      sections: [
        {
          head: ["Product", "Quantity sold", "Revenue", "Avg unit price", "Current stock"],
          body: report.bestSelling.map((row) => [
            row.product.name,
            row.totalQuantity,
            formatMoney(row.totalRevenue, currency),
            formatMoney(row.avgUnitPrice, currency),
            row.currentStock.total,
          ]),
        },
      ],
      footerNote: "Generated by D-Inventory",
    })
  }

  const dateControls = (
    <div className="flex flex-wrap items-center gap-2">
      <Input type="date" value={startDate} onChange={(e) => setStartDate(e.target.value)} className="w-auto" />
      <span className="text-xs text-muted-foreground">to</span>
      <Input type="date" value={endDate} onChange={(e) => setEndDate(e.target.value)} className="w-auto" />
      <DownloadMenu
        className="ml-auto"
        disabled={!query.data}
        groups={[{ items: [{ label: "CSV", onClick: downloadAsCsv }, { label: "PDF", onClick: downloadAsPdf }] }]}
      />
    </div>
  )

  if (query.isLoading) {
    return (
      <div className="space-y-4">
        {dateControls}
        <Skeleton className="h-64 rounded-xl" />
      </div>
    )
  }
  if (query.isError) {
    return (
      <div className="space-y-4">
        {dateControls}
        <ErrorState onRetry={() => query.refetch()} />
      </div>
    )
  }
  const report = query.data
  if (!report) return null

  if (report.totalProducts === 0 || report.bestSelling.length === 0) {
    return (
      <div className="space-y-4">
        {dateControls}
        <EmptyState icon={<Package className="size-6" />} title="No product sales yet" description="Product performance will show up here once you record sales." />
      </div>
    )
  }

  return (
    <div className="space-y-4">
      {dateControls}
      <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
        <div className="rounded-xl border border-border p-4">
          <h3 className="mb-3 text-sm font-semibold">Best selling (by revenue)</h3>
          <ProductList items={report.bestSelling} currency={currency} metric="revenue" />
        </div>
        <div className="rounded-xl border border-border p-4">
          <h3 className="mb-3 text-sm font-semibold">Most quantity sold</h3>
          <ProductList items={report.mostQuantitySold} currency={currency} metric="quantity" />
        </div>
      </div>
    </div>
  )
}
